/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as StockRouteImport } from './routes/stock'
import { Route as CoffretsRouteImport } from './routes/coffrets'
import { Route as ProductionRouteImport } from './routes/production'
import { Route as LivraisonsRouteImport } from './routes/livraisons'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LivraisonsIdRouteImport } from './routes/livraisons.$id'

const StockRoute = StockRouteImport.update({
  id: '/stock',
  path: '/stock',
  getParentRoute: () => rootRouteImport,
} as any)
const CoffretsRoute = CoffretsRouteImport.update({
  id: '/coffrets',
  path: '/coffrets',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductionRoute = ProductionRouteImport.update({
  id: '/production',
  path: '/production',
  getParentRoute: () => rootRouteImport,
} as any)
const LivraisonsRoute = LivraisonsRouteImport.update({
  id: '/livraisons',
  path: '/livraisons',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LivraisonsIdRoute = LivraisonsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => LivraisonsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/livraisons': typeof LivraisonsRouteWithChildren
  '/coffrets': typeof CoffretsRoute
  '/production': typeof ProductionRoute
  '/stock': typeof StockRoute
  '/livraisons/$id': typeof LivraisonsIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/livraisons': typeof LivraisonsRouteWithChildren
  '/coffrets': typeof CoffretsRoute
  '/production': typeof ProductionRoute
  '/stock': typeof StockRoute
  '/livraisons/$id': typeof LivraisonsIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/livraisons': typeof LivraisonsRouteWithChildren
  '/coffrets': typeof CoffretsRoute
  '/production': typeof ProductionRoute
  '/stock': typeof StockRoute
  '/livraisons/$id': typeof LivraisonsIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/coffrets' | '/livraisons' | '/production' | '/stock' | '/livraisons/$id'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/coffrets' | '/livraisons' | '/production' | '/stock' | '/livraisons/$id'
  id:
    | '__root__'
    | '/'
    | '/coffrets'
    | '/livraisons'
    | '/production'
    | '/stock'
    | '/livraisons/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CoffretsRoute: typeof CoffretsRoute
  LivraisonsRoute: typeof LivraisonsRouteWithChildren
  ProductionRoute: typeof ProductionRoute
  StockRoute: typeof StockRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/stock': {
      id: '/stock'
      path: '/stock'
      fullPath: '/stock'
      preLoaderRoute: typeof StockRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/production': {
      id: '/production'
      path: '/production'
      fullPath: '/production'
      preLoaderRoute: typeof ProductionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/coffrets': {
      id: '/coffrets'
      path: '/coffrets'
      fullPath: '/coffrets'
      preLoaderRoute: typeof CoffretsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/livraisons': {
      id: '/livraisons'
      path: '/livraisons'
      fullPath: '/livraisons'
      preLoaderRoute: typeof LivraisonsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/livraisons/$id': {
      id: '/livraisons/$id'
      path: '/$id'
      fullPath: '/livraisons/$id'
      preLoaderRoute: typeof LivraisonsIdRouteImport
      parentRoute: typeof LivraisonsRoute
    }
  }
}

interface LivraisonsRouteChildren {
  LivraisonsIdRoute: typeof LivraisonsIdRoute
}

const LivraisonsRouteChildren: LivraisonsRouteChildren = {
  LivraisonsIdRoute: LivraisonsIdRoute,
}

const LivraisonsRouteWithChildren = LivraisonsRoute._addFileChildren(
  LivraisonsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  CoffretsRoute: CoffretsRoute,
  IndexRoute: IndexRoute,
  LivraisonsRoute: LivraisonsRouteWithChildren,
  ProductionRoute: ProductionRoute,
  StockRoute: StockRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
